server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://[도메인]:3306/test_db?serverTimezone=Asia/Seoul
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver